### ISSUE TITLE
Changing the language on different pages

### ISSUE THREAD

**Issue by TotzkePaul** [hishamco/LanguageSwitcherTagHelper#1]
If I change the language on one page and go to another page and change the language there, I get two language cookies with the same name but different Paths. MVC only sees 1 cookie in the request. This change will ensure the cookie is overwritten no matter which page the cookie is created. 

    private void AppendScript(ref TagHelperOutput output)
        {
            output.Content.AppendHtml($@"
        <script type='text/javascript'>
            function useCookie(code) {{
                var culture = code;
                var uiCulture = code;
                var cookieValue = '{CookieRequestCultureProvider.DefaultCookieName}=c='+code+'|uic='+code+'; Path=/;'; 
                document.cookie = cookieValue; 
                window.location.reload();
            }}
        </script>");
        }`

**Comment by hishamco** [comment]
Thanks @TotzkePaul for mentioning this, I think I need to change many thing in this repo, while it's little bit old 😄

**Comment by hishamco** [comment]
I upgrade the repo, after digging into the code, seems the old code works fine 😄, could you please check the latest change and let me know if the issue still in your side

thanks

**Comment by TotzkePaul** [comment]
The AppendScript that I shared in the original comment is all I had to update to fix my issue. (adding Path=/; to the cookie) Your solution would be a bigger change but I'll try it out in the next couple of days.

**Comment by hishamco** [comment]
Perhaps it was a bug in the underlying APIs, because when I update the packages everything works as expected

thanks
